version: '3.5'

services:
  react-boilerplate_build:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: 'react-boilerplate_build'
    volumes:
      - dist:/usr/src/app/dist

  react-boilerplate_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'react-boilerplate_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  dist:
